<?php

declare(strict_types=1);

function get_username(PDO $pdo, string $username) { // created a connection to the database
    // sql query
    $query = "SELECT username FROM users WHERE username = :username;";
    $statement = $pdo->prepare($query); //  // Prepare the statement to avoid SQL injection
    $statement->bindValue(':username', $username); // // Bind the :username parameter to the actual $username value
    $statement->execute();

    $result = $statement->fetch(PDO::FETCH_ASSOC); // Retrieves the result set generated by a previously executed query.
    return $result;


}

function get_email(PDO $pdo, string $email) { // created a connection to the database
    // sql query
    $query = "SELECT username FROM users WHERE email = :email;";
    $statement = $pdo->prepare($query); //  // Prepare the statement to avoid SQL injection
    $statement->bindValue(':email', $email); // // Bind the :email parameter to the actual $email value
    $statement->execute();

    $result = $statement->fetch(PDO::FETCH_ASSOC); // Retrieves the result set generated by a previously executed query.
    return $result;


}

function set_user(PDO $pdo, $email, $password, $username) { // crea ted a connection to the database
    // sql query
    $query = "INSERT INTO users (username, password, email) VALUES (:username, :password, :email)";
    $statement = $pdo->prepare($query); //  // Prepare the statement to avoid SQL injection
    $statement->bindValue(':username', $username); // // Bind the :email parameter to the actual $email value
    $statement->bindValue(':password', $password); // // Bind the :email parameter to the actual $email value
    $statement->bindValue(':email', $email); // // Bind the :email parameter to the actual $email value
    $statement->execute();


}